

###

PUT http://localhost:3000/profile/1/
Content-Type: application/json

{
    
    "id":1,
    "name":"john5",
    "email":"john@123.com",
    "password":"1237&Abc",
    "age":37,
    "gender":"male",
    "company":"xyz",
    "designation":"abc",
    "about":"john1 xyz"
}

###

GET http://localhost:3000/profile/1/

###

DELETE http://localhost:3000/profile/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9objUiLCJpYXQiOjE2Mjg4Mzc4Nzd9.W85sm0qR7EAXJ_w9dRvILx2mY5LiclrHY3EtdrpzbJI


###
GET http://localhost:3000/profile/
###

POST http://localhost:3000/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9objUiLCJpYXQiOjE2Mjg4Mzc4Nzd9.W85sm0qR7EAXJ_w9dRvILx2mY5LiclrHY3EtdrpzbJI


{
    "id":1,
    "name":"john5",
    "email":"john@123.com",
    "password":"1237&Abc",
    "age":30,
    "gender":"male",
    "company":"xyz",
    "designation":"abc",
    "about":"john1 xyz"

}
###
POST http://localhost:3000/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9objUiLCJpYXQiOjE2Mjg4Mzc4Nzd9.W85sm0qR7EAXJ_w9dRvILx2mY5LiclrHY3EtdrpzbJI


{
    "id":2,
    "name":"rahul3",
    "email":"rahul@123.com",
    "password":"1237&Rahul",
    "age":30,
    "gender":"male",
    "company":"xyz",
    "designation":"abc",
    "about":"rahul xyz"

}

###

POST http://localhost:3000/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9objUiLCJpYXQiOjE2Mjg4Mzc4Nzd9.W85sm0qR7EAXJ_w9dRvILx2mY5LiclrHY3EtdrpzbJI


{
    "id":3,
    "name":"rakesh",
    "email":"rakesh@123.com",
    "password":"1237&Rakesh",
    "age":30,
    "gender":"male",
    "company":"xyz",
    "designation":"abc",
    "about":"rakesh xyz"

}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "name":"john5",
    "email":"john@123.com",
    "password":"1237&Abc"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
     "name":"rakesh",
    "email":"rakesh@123.com",
    "password":"1237&Rakesh"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "name":"rahul3",
    "email":"rahul@123.com",
    "password":"1237&Rahul"
}


###

PUT http://localhost:3000/profile/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9objUiLCJpYXQiOjE2Mjg4Mzc4Nzd9.W85sm0qR7EAXJ_w9dRvILx2mY5LiclrHY3EtdrpzbJI


{
    "id":1,
    "name":"john5",
    "email":"john@123.com",
    "password":"1237&Abc",
    "age":30,
    "gender":"male",
    "company":"xyz",
    "designation":"abc",
    "about":"john1 xyz"
}
